module.exports = [
    {
      date: "2022-04-01",
      name: "Payday",
      source: "Income",
      location: "Checking Account",
      amount: 1000,
    },
    {
      date: "2022-04-01",
      name: "Government Shakedown",
      source: "Taxes",
      location: "Savings Account",
      amount: -300,
    },
    {
      date: "2022-04-01",
      name: "Y.O.L.O",
      source: "Retirement",
      location: "Checking Account",
      amount: -200,
    },
    {
      date: "2022-04-01",
      name: "Rainy day",
      source: "Savings",
      location: "Checking Account",
      amount: -100,
    },
    {
      date: "2022-04-01",
      name: "PayMyDues",
      source: "Credit Card Payment",
      location: "Checking Account",
      amount: -100,
    },
    {
      date: "2022-04-05",
      name: "Residual Income",
      source: "Monthly Birthday Money from Aunt Tilda",
      location: "Savings Account",
      amount: 20,
    },
    {
      date: "2022-04-05",
      name: "Pick me up",
      source: "Coffee",
      location: "Checking Account",
      amount: -4,
    },
    {
      date: "2022-04-05",
      name: "!!Online",
      source: "Internet",
      location: "Credit Account",
      amount: -100,
    },
    {
      date: "2022/04/03",
      name: "I gotta eat",
      source: "Groceries",
      location: "Checking Account",
      amount: -76,
    },
    {
      date: "2022/04/03",
      name: "!PetChef",
      source: "Pet Food",
      location: "Savings Account",
      amount: -7,
    },
  ];